server:
  port: ${API_SERVER_PORT:8080}

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:${KAFKA_SERVERS:localhost:9092}}
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/coindb}
    username: ${DB_USER:${DB_USERNAME:postgres}}
    password: ${DB_PASSWORD:${DB_PASS:}}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  mvc:
    problem-details:
      enabled: true
  autoconfigure:
    exclude:

springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false

app:
  moduleName: api
  heartbeat:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true
  prometheus:
    metrics:
      export:
        enabled: ${MANAGEMENT_PROMETHEUS_ENABLED:true}
  datadog:
    metrics:
      export:
        enabled: false
