spring:
  datasource:
    password: ${DB_PASSWORD}

springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true

cors:
  allowed-origin-patterns: "*"

logging:
  level:
    com.example.demo: DEBUG
    org.springframework.web: DEBUG
