plugins {
	id 'java'
	id 'org.springframework.boot' version '3.4.5'
	id 'io.spring.dependency-management' version '1.1.7'
	id 'org.hibernate.orm' version '6.6.13.Final'
	id 'org.graalvm.buildtools.native' version '0.10.6'
	id 'org.asciidoctor.jvm.convert' version '3.3.2'
	id 'com.google.protobuf' version '0.9.4'
}


dependencies {

	 // Spring Boot core
    implementation 'org.springframework.boot:spring-boot-starter'
    // Test
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
	implementation 'org.springframework.boot:spring-boot-starter-actuator'

//	implementation 'org.apache.kafka:kafka-streams'
//	implementation 'org.springframework.cloud:spring-cloud-bus'
//	implementation 'org.springframework.cloud:spring-cloud-stream'
//	implementation 'org.springframework.cloud:spring-cloud-stream-binder-kafka'
//	implementation 'org.springframework.cloud:spring-cloud-stream-binder-kafka-streams'
	implementation 'org.springframework.kafka:spring-kafka'


//	implementation 'org.springframework.session:spring-session-data-redis'
//	implementation 'org.springframework.session:spring-session-jdbc'
	compileOnly 'org.projectlombok:lombok'
	developmentOnly 'org.springframework.boot:spring-boot-devtools'
	developmentOnly 'org.springframework.boot:spring-boot-docker-compose'

	annotationProcessor 'org.projectlombok:lombok'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testImplementation 'org.springframework.kafka:spring-kafka-test'

	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

	// WebFlux: WebClient & WebSocket support
    
    // Jackson for DTO (JsonNaming, etc.)
    implementation 'com.fasterxml.jackson.core:jackson-databind'
	implementation 'com.fasterxml.jackson.core:jackson-annotations'
    
    // PostConstruct (Jakarta)
    implementation 'jakarta.annotation:jakarta.annotation-api:2.1.1'

	// Binnace connector 

	//dsl json

	//jsoniter

	//postgresql

	//metric
	implementation 'io.micrometer:micrometer-core'

	//inner project shard
	implementation(project(":contracts"))
	implementation(project(":infra_shard"))

}

tasks.named('test') {
	useJUnitPlatform()
}
