plugins {
	id 'java-library'
	id 'io.spring.dependency-management' version '1.1.7'
}


dependencies {


	//auth0
	implementation 'com.auth0:java-jwt:4.5.0'

	//config
	implementation "org.springframework.boot:spring-boot-autoconfigure"
	annotationProcessor "org.springframework.boot:spring-boot-configuration-processor"

	// HTTP client (이 모듈에서 WebClient를 직접 사용한다면 유지)
	implementation  'org.springframework:spring-webflux'
	implementation  'io.projectreactor.netty:reactor-netty'


	// JSON (실제로 쓰는 것만 남기는 것을 권장)
	implementation 'com.fasterxml.jackson.core:jackson-databind'
	implementation 'com.fasterxml.jackson.core:jackson-annotations'
	implementation 'com.dslplatform:dsl-json:2.0.2'
	annotationProcessor 'com.dslplatform:dsl-json:2.0.2'
	implementation 'com.jsoniter:jsoniter:0.9.23'

	// Jakarta annotations
	compileOnly 'jakarta.annotation:jakarta.annotation-api:2.1.1'

	// Lombok
	compileOnly 'org.projectlombok:lombok'
	annotationProcessor 'org.projectlombok:lombok'

	testImplementation 'org.junit.jupiter:junit-jupiter'
	//okio
	implementation 'com.squareup.okio:okio:3.16.4'
	implementation 'com.squareup.okhttp3:okhttp:5.3.2'

	// inner
	implementation project(":infra_shard")
}

tasks.test {
	useJUnitPlatform()
}